version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: english_uat
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - '3308:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: 103.161.173.59
      DB_PORT: 3308
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: english_uat

volumes:
  mysql-data: